"syn keyword pythonStatement self
"syn keyword pythonStatement in
"syn keyword pythonStatement and
"syn keyword pythonStatement or
"syn keyword pythonStatement not
"syn keyword pythonStatement is
"syn keyword pythonStatement for
"syn keyword pythonStatement import
"syn keyword pythonStatement TODO
